# Generated by Django 5.2 on 2025-05-13 15:18

import backend.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_profile', '0004_alter_student_badges'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='student',
            options={},
        ),
        migrations.AlterField(
            model_name='student',
            name='profile_picture',
            field=models.ImageField(blank=True, help_text='The profile picture of the student.', null=True, storage=backend.storage.ProfilePictureStorage(), upload_to='', verbose_name='Profile Picture'),
        ),
    ]
