# Generated by Django 5.2 on 2025-05-13 15:18

import backend.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clubs', '0007_colorpalette'),
    ]

    operations = [
        migrations.AlterField(
            model_name='club',
            name='banner',
            field=models.ImageField(blank=True, help_text='The banner image of the club.', null=True, storage=backend.storage.ClubBannerStorage(), upload_to='', verbose_name='Club Banner'),
        ),
        migrations.AlterField(
            model_name='club',
            name='logo',
            field=models.ImageField(blank=True, help_text='The logo of the club.', null=True, storage=backend.storage.ClubLogoStorage(), upload_to='', verbose_name='Club Logo'),
        ),
    ]
