# Generated by Django 5.1.6 on 2025-03-04 17:57

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_id', models.CharField(max_length=8, unique=True, validators=[django.core.validators.RegexValidator(message='Student ID must be 8 digits', regex='^\\d{8}$')])),
                ('name', models.CharField(max_length=50)),
                ('password', models.CharField(max_length=128)),
            ],
        ),
    ]
