# Generated by Django 5.2 on 2025-05-13 15:18

import backend.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('add_event', '0004_alter_event_banner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='banner',
            field=models.ImageField(blank=True, help_text='The banner image of the event.', null=True, storage=backend.storage.EventBannerStorage(), upload_to='', verbose_name='Event Banner'),
        ),
    ]
